## The six 2017 unit types as the rules use them, plus the three shot shapes.
##
## The TABLE itself is `constants.nim`, generated by reflecting the pinned
## jar's own `RobotType` (never hand-typed); this file is the derived reading
## of it: the five predicates as the engine's own expressions, the starting
## health, the shot costs and spreads, and the name vocabulary the replay and
## the viewer spell units with.

import constants

export constants

type
  ShotShape* = enum
    ## `RobotControllerImpl.fireSingleShot` / `fireTriadShot` /
    ## `firePentadShot`, and the `fireBulletSpread(dir, toFire, spread)` each
    ## of them calls.
    ssSingle = "single"
    ssTriad = "triad"
    ssPentad = "pentad"

const
  Bc17UnitNames* = ["archon", "gardener", "lumberjack", "soldier", "tank",
                    "scout"]
    ## `RobotType.values()` ordinals 0..5, as every event field and the atlas
    ## spell them.

func shotCost*(shape: ShotShape): float32 =
  case shape
  of ssSingle: singleShotCost
  of ssTriad: triadShotCost
  of ssPentad: pentadShotCost

func shotCount*(shape: ShotShape): int =
  case shape
  of ssSingle: 1
  of ssTriad: 3
  of ssPentad: 5

func shotSpreadDegrees*(shape: ShotShape): float32 =
  ## A single shot passes spread 0 and fires only the centre bullet.
  case shape
  of ssSingle: 0'f32
  of ssTriad: triadSpreadDegrees
  of ssPentad: pentadSpreadDegrees

func canFire*(t: RobotType, shape: ShotShape): bool =
  ## `canFireSingleShot`/`canFireTriadShot`/`canFirePentadShot`'s TYPE half,
  ## verbatim: never an ARCHON, a GARDENER or a LUMBERJACK, and a SCOUT may
  ## fire ONLY singles.
  if t == rtArchon or t == rtGardener or t == rtLumberjack:
    return false
  if shape != ssSingle and t == rtScout:
    return false
  true

func unitName*(t: RobotType): string = Bc17UnitNames[ord(t)]

func maxHealthF*(t: RobotType): float32 =
  ## `type.maxHealth` is an `int` in the engine's table and every expression
  ## that uses it promotes it to float, so the promotion happens once, here.
  float32(RobotSpecs[t].maxHealth)

func bulletCostF*(t: RobotType): float32 =
  ## Likewise for `bulletCost` -- **including ARCHON's `-1`**, which the
  ## round-2999 tiebreak really does add to its own team's total.
  float32(RobotSpecs[t].bulletCost)

func bodyRadius*(t: RobotType): float32 = RobotSpecs[t].bodyRadius
func strideRadius*(t: RobotType): float32 = RobotSpecs[t].strideRadius
func bulletSpeed*(t: RobotType): float32 = RobotSpecs[t].bulletSpeed
func attackPower*(t: RobotType): float32 = RobotSpecs[t].attackPower
func sensorRadius*(t: RobotType): float32 = RobotSpecs[t].sensorRadius
func bulletSightRadius*(t: RobotType): float32 =
  RobotSpecs[t].bulletSightRadius
func startingHealth*(t: RobotType): float32 = RobotSpecs[t].startingHealth
func buildCooldownTurns*(t: RobotType): int = RobotSpecs[t].buildCooldownTurns

func repairPerDormantTurn*(t: RobotType): float32 =
  ## `processBeginningOfTurn`'s `repairRobot(.04f * getType().maxHealth)`,
  ## charged for the first twenty turns of a BUILDABLE robot's life. The
  ## product is float32 and the multiplicand is the int table value promoted.
  0.04'f32 * maxHealthF(t)
