## §Tests item 4 -- the fdlibm port, pinned against the JVM.
##
## `data/bc17/fdlibm_vectors.json` is GENERATED by `tools/JavaBc17Tables.java`
## under the pinned JDK 8 from the pinned oracle jar's own classes. It carries
## two things:
##
##   * 448 BOUNDARY ROWS -- eleven expression shapes over forty curated
##     `(dx, dy)` pairs, plus the eight rotation vectors a triad and a pentad
##     really produce -- each as `(bits(dx), bits(dy), bits(result))`;
##   * ELEVEN DIGESTS over 2 000 000 pseudo-random samples drawn from
##     `java.util.Random(20170101)`, folded two levels deep so neither side
##     needs a 24 MB buffer.
##
## This shard recomputes both **in Nim, from the same recipe**, and compares
## bit-for-bit. A single wrong width or a platform-libm transcendental moves
## a digest, so the 2 000 000 samples are not decoration: they are the reason
## the sandbox can claim the port is the JVM's function and not merely close
## to it.

import std/[json, math, strutils]
import crunchy/sha256
import harness
import bc17_fixture
import battlecode/fdlibm
import battlecode/years/bc17/[geom, ballistics]

let doc = parseJson(readFile(vectorsPath()))

# --- the artefact is the one the Java tool wrote ----------------------------
block:
  check("the vectors ship", doc.hasKey("boundary") and doc.hasKey("digests"))
  checkEq("recorded under the pinned JDK 8", doc["jdk"].getStr()[0 .. 5],
    "1.8.0_")
  checkEq("the sample seed is the pinned one", doc["sample"]["seed"].getInt(),
    20170101)
  checkEq("over two million samples", doc["sample"]["count"].getInt(), 2000000)
  checkEq("in blocks of 65536", doc["sample"]["block"].getInt(), 65536)

# --- the shapes, in Nim -----------------------------------------------------
const Shapes = ["direction_from_deltas", "reduce_wrap", "radians_between",
                "delta_x", "delta_y", "add_dir_x", "add_dir_dist_x",
                "distance_to", "distance_squared_to", "perp_dist", "hit_dist"]

proc shape(which: int, dx, dy: float32): float32 =
  ## The eleven expression shapes of the F3 width table, each one exactly the
  ## engine's own expression -- and the whole point is that they DIFFER from
  ## one another in where the narrowing happens.
  let radians = reduce(float32(fdlibmAtan2(float64(dy), float64(dx))))
  let distSq = dx * dx + dy * dy
  let dist = float32(sqrt(float64(distSq)))
  ## A second direction from the SWAPPED deltas, so the two `calcHitDist`
  ## shapes have a real angle to work on rather than a right angle.
  let radiansB = reduce(float32(fdlibmAtan2(float64(dx), float64(dy))))
  let between = reduce(radiansB - radians)
  case which
  of 0: radians
  of 1: reduce(radians + 3'f32 * FloatPi)
  of 2: between
  of 3: float32(float64(dist) * fdlibmCos(float64(radians)))
  of 4: float32(float64(dist) * fdlibmSin(float64(radians)))
  of 5: dx + float32(fdlibmCos(float64(radians)))
  of 6: dx + float32(float64(dist) * fdlibmCos(float64(radians)))
  of 7: dist
  of 8: distSq
  of 9: float32(abs(float64(dist) * fdlibmSin(float64(between))))
  else: dist * float32(fdlibmCos(float64(between)))

# --- the 448 boundary rows, value for value ---------------------------------
block:
  var rows = 0
  var bad = 0
  var firstBad = ""
  var rotations = 0
  for row in doc["boundary"]:
    let kind = row[0].getStr()
    let a = f32of(row[1].getStr())
    let b = f32of(row[2].getStr())
    let want = uint32(parseHexInt(row[3].getStr()))
    var got: uint32
    if kind == "rotate_left_degrees":
      inc rotations
      got = bits(dirRads(b).rotateLeftDegrees(a).radians)
    elif kind == "rotate_right_degrees":
      inc rotations
      got = bits(dirRads(b).rotateRightDegrees(a).radians)
    else:
      let which = Shapes.find(kind)
      if which < 0:
        inc bad
        if firstBad.len == 0: firstBad = "unknown shape " & kind
        continue
      got = bits(shape(which, a, b))
    inc rows
    if got != want:
      inc bad
      if firstBad.len == 0:
        firstBad = kind & "(" & row[1].getStr() & ", " & row[2].getStr() &
          ") = 0x" & toHex(got) & " want " & row[3].getStr()
  checkEq("the artefact carries every boundary row", rows, 448)
  checkEq("including the eight triad/pentad rotations", rotations, 8)
  if bad > 0: echo "  first divergence: ", firstBad
  checkEq("and the Nim port reproduces every one of them bit for bit", bad, 0)

# --- the eleven digests over two million samples ----------------------------
block:
  ## `sha256( concat over blocks of sha256(block bytes) )`, where a block is
  ## at most 65 536 rows of `(bits(dx), bits(dy), bits(result))` big-endian.
  ## Two levels because the Nim sha256 is one-shot.
  let count = doc["sample"]["count"].getInt()
  let blockSamples = doc["sample"]["block"].getInt()
  var rng = initJavaRandom(doc["sample"]["seed"].getInt())
  var buf = newSeq[string](Shapes.len)
  var outer = newSeq[string](Shapes.len)
  for s in 0 ..< Shapes.len:
    buf[s] = newStringOfCap(blockSamples * 12)
  proc digestOf(data: string): string =
    for b in sha256(data): result.add(char(b))
  proc be(dst: var string, v: uint32) =
    dst.add(char((v shr 24) and 0xFF'u32))
    dst.add(char((v shr 16) and 0xFF'u32))
    dst.add(char((v shr 8) and 0xFF'u32))
    dst.add(char(v and 0xFF'u32))
  var inBlock = 0
  for i in 0 ..< count:
    let dx = (rng.nextFloat() - 0.5'f32) * 200'f32
    let dy = (rng.nextFloat() - 0.5'f32) * 200'f32
    for s in 0 ..< Shapes.len:
      buf[s].be(bits(dx))
      buf[s].be(bits(dy))
      buf[s].be(bits(shape(s, dx, dy)))
    inc inBlock
    if inBlock == blockSamples:
      for s in 0 ..< Shapes.len:
        outer[s].add(digestOf(buf[s]))
        buf[s].setLen(0)
      inBlock = 0
  if inBlock > 0:
    for s in 0 ..< Shapes.len:
      outer[s].add(digestOf(buf[s]))
  for s, name in Shapes:
    var hex = ""
    for b in sha256(outer[s]): hex.add(toHex(b, 2).toLowerAscii())
    checkEq("the " & name & " digest over 2 000 000 samples",
      hex, doc["digests"][name].getStr())

# --- the port is not a platform-libm wrapper --------------------------------
block:
  ## If `fdlibmSin` were `sin` this shard would still pass every vector on
  ## THIS machine and diverge on the CI runner or in wasm. So prove it is a
  ## different function: find a double where the two disagree in the last
  ## bits.
  var disagreements = 0
  var firstX = 0.0
  var x = 0.1
  for i in 0 ..< 200000:
    x = x + 1.7e-5
    if x > 3.9: x = x - 7.8
    if fdlibmSin(x) != sin(x) or fdlibmCos(x) != cos(x):
      if disagreements == 0: firstX = x
      inc disagreements
  check("fdlibmSin/fdlibmCos differ from the platform libm somewhere, so " &
    "the port is a PORT and not a wrapper", disagreements > 0)
  if disagreements > 0:
    echo "  ", disagreements, " disagreements in 200 000 doubles, first at x=",
      firstX
  ## atan2 is the one the direction constructor calls on every sample.
  var atanDisagreements = 0
  for i in 1 .. 50000:
    let yy = float64(i) * 0.0003 - 7.5
    let xx = 1.0 - float64(i) * 0.00017
    if fdlibmAtan2(yy, xx) != arctan2(yy, xx): inc atanDisagreements
  check("and so does fdlibmAtan2", atanDisagreements > 0)

# --- the guarded range ------------------------------------------------------
block:
  ## The two kernels are only valid on `[-4, 4]`; outside it the port RAISES
  ## rather than returning a plausible wrong number, because a silent wrong
  ## number is a parity divergence nobody finds.
  var raised = 0
  for v in [4.5, -4.5, 1e9, -1e9]:
    try:
      discard fdlibmSin(v)
    except CatchableError, Defect:
      inc raised
  checkEq("fdlibmSin raises outside [-4, 4]", raised, 4)
  raised = 0
  for v in [4.5, -4.5, 1e9, -1e9]:
    try:
      discard fdlibmCos(v)
    except CatchableError, Defect:
      inc raised
  checkEq("and so does fdlibmCos", raised, 4)
  ## Every argument the sim ever passes is a reduced angle, so the guard is
  ## never hit in play: `reduce` bounds it by (float)pi.
  check("a reduced angle is always inside the guard",
    abs(float64(reduce(1e7'f32))) <= 4.0)

# --- calcHitDist uses the two opposite shapes -------------------------------
block:
  ## The hoisted `calcHitDist` must agree with the two shapes computed
  ## separately -- `perp_dist` in float64 and `hit_dist` with the cosine
  ## narrowed first.
  let start = loc(0, 0)
  let finish = loc(10, 0)
  let toFinish = directionTo(start, finish)
  let target = loc(5, 0.5)
  let d = calcHitDist(start, finish, 10'f32, toFinish, target, 1'f32)
  let distToTarget = distanceTo(start, target)
  let between = radiansBetween(toFinish, directionTo(start, target))
  let perp = float32(abs(float64(distToTarget) * fdlibmSin(float64(between))))
  let hit = distToTarget * float32(fdlibmCos(float64(between)))
  let half = float32(sqrt(float64(1'f32 * 1'f32 - perp * perp)))
  checkEq("calcHitDist is exactly hitDist - halfChordDist in float32",
    bits(d), bits(hit - half))

finish("test_bc17_fdlibm")
