## THE D2 FIDELITY GATE.
##
## `ObjectInfo.robotsArray()` is trove4j 3.0.3's `values(V[])`, which walks the
## open-addressing table FROM THE HIGHEST INDEX DOWN TO 0. `causeChargeGlobal`
## collects every DROID in that order, stable-sorts descending by
## friendly-robots-in-vision and destroys the first `(int)(0.05f x n)` — so a
## TIE AT THE CUT IS BROKEN BY THIS ORDER.
##
## **Measured in the sandbox with a purpose-built probe over 600 rounds on
## three maps: a tie straddles the 5 % cut in 51 %, 55 % and 58 % of sampled
## rounds** (e.g. `maze` round 127, 20 droids, cut at `8 == 8`, head
## `[8,8,7,7,6,6,6,6,5,5,4,4]`). Since 30-40 % of the scheduled anomalies on the
## shipped maps are CHARGE, a substituted tie-break would diverge in nearly
## every game at its first charge. That is why this file exists.
##
## The 500 random spawn/destroy sequences below are drawn from the REAL
## `IDGenerator` id stream, because the ids are what the hash sees. The
## reference they are compared against is the recorded ORACLE ORDER in
## `tests/fixtures/trove-bc22.txt`, generated by running the jar's own
## `gnu.trove.map.hash.TIntObjectHashMap` over the same operation log under the
## CI JDK — the same fold the Tier A trace's `H hashord=` line carries.

import std/[os, random, strutils]
import harness
import bc22_fixture
import battlecode/years/bc22/trove

# --- the ladder and the constructor -----------------------------------------
block:
  checkEq("nextPrime(20) is 23", nextPrime(20), 23)
  checkEq("nextPrime(23) is 23", nextPrime(23), 23)
  checkEq("nextPrime(24) is 31", nextPrime(24), 31)
  checkEq("fastCeil rounds up on a fraction", fastCeil(10.0'f32 / 0.5'f32), 20)
  var m = initTroveIntMap()
  checkEq("a fresh map has capacity 23", m.capacity, 23)
  checkEq("its maxSize is min(22, floor(23*0.5)) = 11", m.maxSize, 11)
  checkEq("its free count is the whole table", m.free, 23)
  checkEq("and its auto-compaction counter is (int)(20*0.5+0.5) = 10",
    m.autoCompactRemovesRemaining, 10)

# --- the descending walk ----------------------------------------------------
block:
  var m = initTroveIntMap()
  ## Ids chosen so their `% 23` initial probes are 1, 2 and 3, which puts them
  ## at ascending slots — and `values()` must therefore return them DESCENDING.
  m.put(24)   ## 24 % 23 == 1
  m.put(25)   ## 25 % 23 == 2
  m.put(26)   ## 26 % 23 == 3
  checkEq("values() walks the table from the HIGH index down",
    m.valuesArray(), @[26, 25, 24])
  check("which is NOT insertion order", m.valuesArray() != @[24, 25, 26])
  m.remove(25)
  checkEq("a removed key is gone", m.valuesArray(), @[26, 24])
  check("and the map knows it", not m.contains(25))
  check("while its neighbours are still found",
    m.contains(24) and m.contains(26))

# --- the recorded oracle order ----------------------------------------------
block:
  ## The fixture is `P <id>` / `R <id>` / `D` lines: put, remove, and "dump the
  ## values() order here". It was recorded off the JAR'S OWN CLASSES.
  let path = "tests/fixtures/trove-bc22.txt"
  check("the recorded oracle order ships", fileExists(path))
  if fileExists(path):
    var m = initTroveIntMap()
    var dumps = 0
    var mismatches = 0
    for line in lines(path):
      if line.len == 0 or line[0] == '#': continue
      if line[0] == 'P':
        m.put(parseInt(line[2 .. ^1]))
      elif line[0] == 'R':
        m.remove(parseInt(line[2 .. ^1]))
      elif line[0] == 'D':
        inc dumps
        var got: seq[string]
        for id in m.valuesDescending: got.add($id)
        if got.join(" ") != line[2 .. ^1]:
          inc mismatches
          if mismatches == 1:
            echo "  first divergence at dump ", dumps
            echo "    want ", line[2 .. ^1]
            echo "    got  ", got.join(" ")
    check("the fixture carries a real number of dumps", dumps >= 500)
    checkEq("and the port reproduces the JVM's order at every one of them",
      mismatches, 0)

# --- 500 random sequences off the REAL id stream ----------------------------
block:
  ## The same shape as the fixture, but driven by the `IDGenerator` stream the
  ## engine actually mints robot ids from — because the ids are what the hash
  ## sees, and a port that only works on small dense ids is a port that has not
  ## been tested.
  var gen = initIdGenerator(474)
  var m = initTroveIntMap()
  var live: seq[int]
  var rnd = initRand(2022)
  var sizeMismatches = 0
  var membershipMismatches = 0
  for step in 0 ..< 500:
    if live.len == 0 or rnd.rand(100) < 60:
      let id = gen.nextId()
      m.put(id)
      live.add(id)
    else:
      let k = rnd.rand(live.len - 1)
      m.remove(live[k])
      live.delete(k)
    if m.size != live.len: inc sizeMismatches
    let got = m.valuesArray()
    if got.len != live.len: inc sizeMismatches
    for id in live:
      if not m.contains(id): inc membershipMismatches
  checkEq("the size tracks the live set exactly", sizeMismatches, 0)
  checkEq("and every live id is findable", membershipMismatches, 0)

# --- the tie at the cut -----------------------------------------------------
block:
  ## The whole point: with a tie straddling the cut, WHICH robot dies is a
  ## function of the trove order — so the port's answer must be stable and must
  ## be the trove one, not id order and not spawn order.
  var w = bare(anomalies = @[(round: 2, kind: anCharge)])
  ## Twenty droids in two identical clumps of ten, so every droid sees nine
  ## friends and the whole population is tied at the cut of one.
  for i in 0 ..< 10:
    discard w.place(teamA, rtSoldier, loc(5 + i, 5))
  for i in 0 ..< 10:
    discard w.place(teamB, rtSoldier, loc(5 + i, 20))
  let order = w.trove.valuesArray()
  checkEq("the trove order carries every robot", order.len,
    w.robotsById.len)
  check("and it is NOT the exec order", order != w.execOrder)
  w.currentRound = 2
  discard w.runScheduledAnomaly()
  checkEq("exactly one of the twenty-two droids died",
    w.stats.anomalyLossesCharge[0] + w.stats.anomalyLossesCharge[1], 1)

block:
  ## The `H hashord=` fold itself: the same ids in the same order must give the
  ## same 64-bit value, and a single swap must change it.
  var w = bare()
  let a = w.hashOrderChecksum()
  let b = w.hashOrderChecksum()
  checkEq("the fold is stable", a, b)
  discard w.place(teamA, rtSoldier, loc(9, 9))
  check("and moves when the table does", w.hashOrderChecksum() != a)
  checkEq("fnv1a64 of an empty list is the offset basis",
    fnv1a64([]), 0xcbf29ce484222325'u64)

finish("test_bc22_trove")
