## `java.util.Random` + `IDGenerator` parity, against recorded Java vectors.
##
## `tests/fixtures/java_random_vectors.json` is generated by
## `tools/JavaRandomVectors.java` under a real JDK (CI regenerates it and
## diffs — see `.github/workflows/ci.yml`). Floats and doubles are compared
## by their exact BIT PATTERNS, not by tolerance: this port exists so cheese
## spawns and robot ids line up with the Java engine draw for draw, and
## "close enough" is a silent, match-long divergence.

import std/[json, os, strutils]
import battlecode/rng

proc fixturePath(): string =
  currentSourcePath().parentDir() / "fixtures" / "java_random_vectors.json"

var failures = 0

proc check(name: string, ok: bool) =
  if not ok:
    echo "FAIL ", name
    inc failures

let doc = parseJson(readFile(fixturePath()))
let draws = doc["draws"].getInt()

for entry in doc["seeds"]:
  let seed = entry["seed"].getInt()
  let tag = "seed " & $seed

  block:
    var rng = initJavaRandom(seed)
    var ok = true
    for i, want in entry["next_int"].getElems():
      if int(rng.nextInt()) != want.getInt(): ok = false; break
    check(tag & " nextInt()", ok)

  block:
    var rng = initJavaRandom(seed)
    var ok = true
    for i, want in entry["next_int_bound"].getElems():
      if int(rng.nextInt(1 + (i mod 97))) != want.getInt(): ok = false; break
    check(tag & " nextInt(bound)", ok)

  block:
    var rng = initJavaRandom(seed)
    var ok = true
    for want in entry["next_int_range"].getElems():
      if int(rng.nextInt(-4, 4)) != want.getInt(): ok = false; break
    check(tag & " nextInt(-4, 4)", ok)

  block:
    var rng = initJavaRandom(seed)
    var ok = true
    for want in entry["next_float"].getElems():
      let got = rng.nextFloat()
      if cast[int32](got) != int32(want.getInt()): ok = false; break
    check(tag & " nextFloat() bit pattern", ok)

  block:
    var rng = initJavaRandom(seed)
    var ok = true
    for want in entry["next_double"].getElems():
      let got = rng.nextDouble()
      if cast[int64](got) != int64(want.getBiggestInt()): ok = false; break
    check(tag & " nextDouble() bit pattern", ok)

  block:
    var rng = initJavaRandom(seed)
    var ok = true
    for want in entry["next_boolean"].getElems():
      if int(ord(rng.nextBoolean())) != want.getInt(): ok = false; break
    check(tag & " nextBoolean()", ok)

  block:
    var gen = initIdGenerator(seed)
    var ok = true
    for want in entry["ids"].getElems():
      if gen.nextId() != want.getInt(): ok = false; break
    check(tag & " IDGenerator ids (across a block boundary)", ok)

# The rejection loop must actually be reachable, or the "both branches" claim
# above is untested: a bound of 3 rejects roughly one draw in 2^31/3.
check("nextInt(bound) exercises a non-power-of-two bound", draws >= 1000)

if failures > 0:
  quit("test_rng: " & $failures & " check(s) failed", 1)
echo "test_rng: ok (", draws, " draws x ", doc["seeds"].len, " seeds)"
