## bc21's economy: the Enlightenment Center's passive income, the slanderer's
## embezzle curve, and the breakpoint table both chassis budget against.
##
## PURE ARITHMETIC AND TABLES. Nothing here touches the world; the end-of-round
## sweep that APPLIES this income (and the camouflage that ends a slanderer's
## life as a slanderer) is in `votes.nim`, because the engine does both inside
## the single `objectInfo.eachRobot` sweep of `GameWorld.processEndOfRound`.
##
## THE TWO CURVES ARE COMMITTED TABLES, NOT RE-DERIVED FORMULAS.
## `RobotType.getPassiveInfluence` is
##
##     ENLIGHTENMENT_CENTER: (int) Math.ceil(0.2f * Math.sqrt(roundNum))
##     SLANDERER (roundsAlive <= 50):
##       (int)(influence * (1.0/50 + 0.03f * Math.exp(-0.001f * influence)))
##
## `Math.sqrt` is exactly rounded by IEEE-754 and needs nothing. `Math.exp` is
## a HotSpot intrinsic and is allowed to differ from the reference by 1 ulp, and
## the platform libm this port would otherwise link is a DIFFERENT function
## natively and under emscripten. Three mechanisms, in order:
##
##   1. `src/battlecode/fdlibm.nim` is the reference `exp` bit for bit, so
##      native and wasm always agree with each other;
##   2. `data/bc21/embezzle.json` commits the resulting integer income for
##      EVERY influence in [1, 4096] — the whole range any real doctrine builds
##      in — and the sim reads the table there, so the hot path is a lookup;
##   3. the `parity-oracle-bc21` job regenerates both tables under the CI JDK 8
##      and BYTE-DIFFS them, and compares Java against this Nim for 4096
##      log-spaced values in (4096, 1e8].
##
## The WIDTHS in `embezzleAt` are the reason the generated breakpoint table
## reproduces California Roll's shipped constants exactly: `-0.001f * x` is a
## FLOAT multiplication widened to `double` only inside `exp`, and `0.03f` is a
## float widened against a double.

import std/[json, math, os]
import ../../fdlibm
import constants

const
  EcPassiveMaxRound* = 1500
  EmbezzleMaxInfluence* = 4096

var
  ecPassiveTable: seq[int]
  embezzleTable: seq[int]
  breakpointTable: seq[int]
  tablesLoaded = false

proc bc21DataRoot*(): string =
  ## `/data` is where emscripten mounts the preloaded directory in the wasm
  ## bundle; `data` is the repo layout the container and the tests use.
  ##
  ## `getAppDir()` is DELIBERATELY not a candidate: under emscripten it walks
  ## `os.getApplAux`, whose `readlink("/proc/self/exe")` returns -1 and whose
  ## next line is a `Natural` conversion that raises before anything is opened.
  for candidate in ["data", "/data", "/workspace/battlecode/data"]:
    if dirExists(candidate / "maps" / "bc21"):
      return candidate
  "data"

func ecPassiveAt*(roundNum: int): int =
  ## `(int) Math.ceil(0.2f * Math.sqrt(roundNum))`, computed. `0.2f` widens to
  ## the double 0.20000000298023224 exactly as Java does, and `Math.sqrt` is
  ## exactly rounded on every IEEE-754 machine, so this needs no table — the
  ## committed one exists so CI can prove that claim.
  if roundNum <= 0: return 0
  int(ceil(float64(PassiveInfluenceRatioEnlightenmentCenter) *
           sqrt(float64(roundNum))))

func embezzleAt*(influence: int): int =
  ## `(int)(influence * (1.0/50 + 0.03f * exp(-0.001f * influence)))`, with
  ## every Java width reproduced and the reference `exp`.
  if influence <= 0: return 0
  let expArg = float64(float32(-EmbezzleDecayFactor) * float32(influence))
  let rate = 1.0 / float64(EmbezzleNumRounds) +
             float64(EmbezzleScaleFactor) * fdlibmExp(expArg)
  int(float64(influence) * rate)

proc loadEconomyTables*() =
  if tablesLoaded: return
  let root = bc21DataRoot()
  let ecPath = root / "bc21" / "ec_passive.json"
  let embPath = root / "bc21" / "embezzle.json"
  for path in [ecPath, embPath]:
    if not fileExists(path):
      raise newException(IOError,
        "a bc21 economy table is missing: no " & path &
        " (in the wasm bundle this means the preloaded data package did not " &
        "mount). Both are generated by tools/JavaBc21Tables.java and committed.")
  let ecDoc = parseJson(readFile(ecPath))
  ecPassiveTable = @[0]
  for v in ecDoc["income"]: ecPassiveTable.add(v.getInt())
  if ecPassiveTable.len != EcPassiveMaxRound + 1:
    raise newException(IOError,
      "data/bc21/ec_passive.json has " & $(ecPassiveTable.len - 1) &
      " rounds, expected " & $EcPassiveMaxRound)
  let embDoc = parseJson(readFile(embPath))
  embezzleTable = @[0]
  for v in embDoc["income"]: embezzleTable.add(v.getInt())
  if embezzleTable.len != EmbezzleMaxInfluence + 1:
    raise newException(IOError,
      "data/bc21/embezzle.json has " & $(embezzleTable.len - 1) &
      " influence rows, expected " & $EmbezzleMaxInfluence)
  breakpointTable = @[]
  for v in embDoc["breakpoints"]: breakpointTable.add(v.getInt())
  tablesLoaded = true

proc ecPassive*(roundNum: int): int =
  ## The Enlightenment Center's income for this round, from the committed
  ## JDK-generated table inside its range and from the formula outside it.
  loadEconomyTables()
  if roundNum <= 0: return 0
  if roundNum <= EcPassiveMaxRound: return ecPassiveTable[roundNum]
  ecPassiveAt(roundNum)

proc embezzle*(influence: int): int =
  ## A slanderer's per-round payment to its parent Center, from the committed
  ## table inside [1, 4096] and from the fdlibm formula outside it.
  loadEconomyTables()
  if influence <= 0: return 0
  if influence <= EmbezzleMaxInfluence: return embezzleTable[influence]
  embezzleAt(influence)

proc slandererBreakpoints*(): seq[int] =
  ## The ascending influence values at which the embezzle income increases —
  ## the only influences a slanderer is ever worth building at. GENERATED from
  ## the engine's own formula, never typed in, and byte-identical to the table
  ## California Roll shipped in `src/maxecosushi/EnlightmentCenter.java:21`,
  ## which is the cross-check that the port reproduced the formula and not a
  ## lookalike.
  loadEconomyTables()
  breakpointTable

proc bestSlandererInfluence*(budget: int): int =
  ## The largest breakpoint this Center can afford, or 0 when it cannot afford
  ## the first one (21).
  if budget <= 0: return 0
  var best = 0
  for value in slandererBreakpoints():
    if value <= budget: best = value
    else: break
  best

proc passiveInfluenceFor*(kind: RobotKind, influence, roundsAlive,
                          roundNum: int): int =
  ## `RobotType.getPassiveInfluence`, dispatched by type. Kept as a `func` over
  ## the two procs above so the round loop reads like the engine's.
  case kind
  of rtEnlightenmentCenter: ecPassive(roundNum)
  of rtSlanderer:
    if roundsAlive <= EmbezzleNumRounds: embezzle(influence) else: 0
  else: 0
