#!/usr/bin/env node
// Regenerate `data/bc19/tables.json` — the WHOLE finite arithmetic domain of
// the 2019 rule set — from the running Node's own `Math` and from the pinned
// engine's own `coldbrew/specs.json`.
//
// bc19 has exactly TWO non-integer operations on any gameplay path and both
// have finite domains, so this is not a sample: it is the entire domain, and
// the runtime therefore has NO `sqrt`, NO `pow`, NO `exp` and no float64
// accumulation at all.
//
//   1. `Math.ceil(Math.sqrt(signal_radius))` — `coldbrew/game.js:834` and
//      `coldbrew/action_record.js:329`. Domain: the integers 0 .. 7938
//      (`2*(MAX_BOARD_SIZE-1)^2`), all 7 939 of them.
//   2. `Math.floor(a / b)` in the reclaim — `coldbrew/action_record.js:305-306`
//      — where `a` is `target.karbonite + CONSTRUCTION_KARBONITE/2` (a
//      HALF-INTEGER, because `15/2` and `25/2` are not integers) or
//      `target.fuel`, and `b` is `rad_to_attacker`, the attacker's own squared
//      distance to the square being processed. `b` ranges over the r^2 values
//      reachable inside a PREACHER's blast plus its own square:
//      {0, 1, 2, 4, 5, 8, 9, 10, 13, 16}.
//      Both cases are tabled ONCE, keyed by the DOUBLED numerator, so
//      `floor_half_div[rad][2*a]` answers both.
//
//   `b == 0` is the attacker's own square. In JavaScript `Math.floor(n/0)` is
//   `Infinity` for `n > 0` and `NaN` for `n === 0`, and the caller is
//   `Math.min(held + reclaimed, capacity)` — so `Infinity` CLAMPS TO THE
//   CAPACITY and `NaN` is never read, because the robot is deleted on the very
//   next line. Both are recorded here as the sentinel **-1 = "clamp to the
//   receiver's capacity"** and **-2 = "NaN, unreadable"**, and
//   `years/bc19/resources.nim` pins the `rad == 0` case to the capacity clamp.
//
// Usage:
//   node tools/JsBc19Tables.mjs --engine <checkout> --out data/bc19/tables.json
//   node tools/JsBc19Tables.mjs --engine <checkout> --check

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname, join } from 'path';

function arg(name, dflt) {
  const i = process.argv.indexOf('--' + name);
  if (i < 0) return dflt;
  const v = process.argv[i + 1];
  return (v === undefined || v.startsWith('--')) ? true : v;
}

const engineDir = resolve(String(arg('engine', 'engine')));
const outPath = resolve(String(arg('out', 'data/bc19/tables.json')));
const check = arg('check', false) === true;

const specs = JSON.parse(
  readFileSync(join(engineDir, 'coldbrew', 'specs.json'), 'utf8'));

const MAX_R2 = 2 * Math.pow(specs.MAX_BOARD_SIZE - 1, 2);   // 7938
const RADS = [0, 1, 2, 4, 5, 8, 9, 10, 13, 16];
const MAX_DOUBLED_NUMERATOR = 550;    // numerator 0 .. 275 in halves

const ceilSqrt = [];
for (let r2 = 0; r2 <= MAX_R2; r2++) ceilSqrt.push(Math.ceil(Math.sqrt(r2)));

const floorHalfDiv = {};
for (const rad of RADS) {
  const row = [];
  for (let n2 = 0; n2 <= MAX_DOUBLED_NUMERATOR; n2++) {
    const v = Math.floor((n2 / 2) / rad);
    if (Number.isNaN(v)) row.push(-2);
    else if (!Number.isFinite(v)) row.push(-1);
    else row.push(v);
  }
  floorHalfDiv[String(rad)] = row;
}

const doc = {
  note: [
    'GENERATED by tools/JsBc19Tables.mjs from the pinned battlecode19',
    'checkout under the pinned Node. Do not edit: parity-oracle-bc19',
    'regenerates this file and byte-diffs it, and tests/test_bc19_arith.nim',
    'asserts every value in it against the Nim port.',
    'floor_half_div is keyed by rad and indexed by TWICE the numerator, so',
    'floor_half_div[rad][2*a] == Math.floor(a/rad) for half-integer a.',
    'In that table -1 means Infinity (the caller clamps to capacity) and -2',
    'means NaN (never read: the robot is deleted on the next line).'
  ],
  engine_commit: '80cf1cc535ec5a30559274aa1b49807ad4859925',
  node_version: process.version,
  specs,
  max_signal_radius: MAX_R2,
  reclaim_divisors: RADS,
  max_doubled_numerator: MAX_DOUBLED_NUMERATOR,
  ceil_sqrt: ceilSqrt,
  floor_half_div: floorHalfDiv
};

const text = JSON.stringify(doc) + '\n';

if (check) {
  if (!existsSync(outPath)) {
    console.error(`::error::${outPath} is missing`);
    process.exit(1);
  }
  if (readFileSync(outPath, 'utf8') !== text) {
    console.error(`::error::${outPath} does not match a regeneration from the ` +
      `pinned engine under node ${process.version}`);
    process.exit(1);
  }
  console.log(`ok ${outPath}: ${ceilSqrt.length} ceil(sqrt(r2)) values and ` +
    `${RADS.length} reclaim divisors`);
} else {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, text);
  console.log(`wrote ${outPath}: ${ceilSqrt.length} ceil(sqrt(r2)) values and ` +
    `${RADS.length} reclaim divisors`);
}
