## The rising water: the committed level table, the one-ring-per-round flood
## fill, and drowning.
##
## THE WATER LEVEL IS A COMMITTED TABLE, NOT A FORMULA.
## `GameConstants.getWaterLevel` is
##
##     (float)(Math.exp(0.0028x - 1.38*Math.sin(0.00157x - 1.73)
##                      + 1.38*Math.sin(-1.73)) - 1)
##
## and `Math.exp` / `Math.sin` are HotSpot intrinsics that are not bit-identical
## to any libm this port would link natively or under emscripten. The function
## depends only on the round number, so `tools/JavaWaterLevels.java` emits every
## value in `data/bc20/water_levels.json` as a float32 BIT PATTERN under the CI
## JDK, the file is COMMITTED, and the `parity-oracle` job regenerates and
## byte-diffs it as a BLOCKING step. Bit-exact against Java by construction, on
## every platform, with no libm in the loop.
##
## `floodfill` snapshots the flooded set BEFORE it changes anything, which is
## what makes the flood advance exactly one ring per round.

import std/[json, os, strutils]
import world

const WaterTableMaxRound* = 1500

var
  waterTable: seq[float32]
  waterTableLoaded = false

proc bc20DataRoot*(): string =
  ## `/data` is where emscripten mounts the preloaded directory in the wasm
  ## bundle; `data` is the repo layout the container and the tests use.
  ##
  ## `getAppDir()` is DELIBERATELY not a candidate: under emscripten it walks
  ## `os.getApplAux`, whose `readlink("/proc/self/exe")` returns -1 and whose
  ## next line is a `Natural` conversion that raises before anything is opened.
  for candidate in ["data", "/data", "/workspace/battlecode/data"]:
    if dirExists(candidate / "maps" / "bc20"):
      return candidate
  "data"

proc loadWaterTable*() =
  if waterTableLoaded: return
  let path = bc20DataRoot() / "bc20" / "water_levels.json"
  if not fileExists(path):
    raise newException(IOError,
      "the bc20 water-level table is missing: no " & path &
      " (in the wasm bundle this means the preloaded data package did not " &
      "mount). It is generated by tools/JavaWaterLevels.java and committed.")
  let doc = parseJson(readFile(path))
  waterTable = @[]
  for entry in doc["levels"]:
    let bits = uint32(parseHexInt(entry.getStr()))
    waterTable.add(cast[float32](bits))
  if waterTable.len != WaterTableMaxRound + 1:
    raise newException(IOError,
      "the bc20 water-level table has " & $waterTable.len &
      " entries, expected " & $(WaterTableMaxRound + 1))
  waterTableLoaded = true

proc waterLevelAt*(round: int): float32 =
  ## `GameConstants.getWaterLevel(round)`, from the committed table. Rounds
  ## past the table's end clamp to its last value; the bc20 variant caps at
  ## 1500, and the chassis look ahead by at most 400 rounds, so the clamp is
  ## only ever reached by a doctrine planning past the end of the game.
  loadWaterTable()
  if round <= 0: return waterTable[0]
  waterTable[min(round, WaterTableMaxRound)]

proc updateWaterLevel*(w: World) =
  w.waterLevel = waterLevelAt(w.currentRound)

proc floodfill*(w: World) =
  ## `GameWorld.floodfill`. The origin set is SNAPSHOTTED first, so the flood
  ## advances exactly one ring per round; `setFloodStatus` destroys any robot
  ## standing on a newly flooded tile that cannot fly.
  var origins: seq[int]
  for i in 0 ..< w.flooded.len:
    if w.flooded[i]: origins.add(i)
  for i in origins:
    let center = w.indexToLoc(i)
    for d in AllDirs:
      let target = center + d
      if not w.onTheMap(target): continue
      let j = w.idx(target)
      if w.flooded[j]: continue
      if float32(w.elevation[j]) >= w.waterLevel: continue
      w.setFloodStatus(j, true)

proc roundWaterReaches*(level: int): int =
  ## The first round at which the water is strictly above `level`, i.e. the
  ## round a tile at that elevation floods if it is next to water. Returns
  ## `WaterTableMaxRound + 1` when the water never gets there inside the cap.
  loadWaterTable()
  for r in 0 .. WaterTableMaxRound:
    if waterTable[r] > float32(level):
      return r
  WaterTableMaxRound + 1

proc floodStageFor*(level: float32): int =
  ## Which integer elevation the water has just reached — the `flood_stage`
  ## beat the viewer draws. 0 while the water is below elevation 1.
  if level < 1.0'f32: 0 else: int(level)
